//
//  NotificationNameConstant.h
//  ArVideoDemo
//
//  Created by Anshul on 23/11/16.
//  Copyright © 2016 Kiwi, Inc. All rights reserved.
//

#ifndef NotificationNameConstant_h
#define NotificationNameConstant_h

static NSString *const NOTIFICATION_SELF_VIDEO_CHAT_WILL_CONNECT = @"NOTIFICATION_SELF_VIDEO_CHAT_WILL_CONNECT";
static NSString *const NOTIFICATION_SELF_VIDEO_CHAT_WILL_RECONNECT = @"NOTIFICATION_SELF_VIDEO_CHAT_WILL_RECONNECT";
static NSString *const NOTIFICATION_SELF_REVEAL_IDENTITY = @"NOTIFICATION_SELF_REVEAL_IDENTITY";
static NSString *const REMOTE_NOTIFICATION_PIXELATION = @"REMOTE_NOTIFICATION_PIXELATION";
static NSString *const NOTIFICATION_PIXELATION_STARTED = @"NOTIFICATION_PIXELATION_STARTED";
static NSString *const NOTIFICATION_PIXELATION_STOPPED = @"NOTIFICATION_PIXELATION_STOPPED";
static NSString *const NOTIFICATION_SELF_VIDEO_CHAT_WILL_CONNECT_FAILED = @"NOTIFICATION_SELF_VIDEO_CHAT_WILL_CONNECT_FAILED";//Don't use this. This is error for getiing session from server. Rename this

static NSString *const NOTIFICATION_ASK_USER_PERMISSION = @"NOTIFICATION_ASK_USER_PERMISSION";
static NSString *const NOTIFICATION_PERMISSION_DENIED = @"NOTIFICATION_PERMISSION_DENIED";
static NSString *const NOTIFICATION_FOR_VOICE_VIEW_TEXT = @"NOTIFICATION_FOR_VOICE_VIEW_TEXT";

static NSString *const NOTIFICATION_SELF_VIDEO_CHAT_CONNECTED = @"NOTIFICATION_SELF_VIDEO_CHAT_CONNECTED";
static NSString *const NOTIFICATION_SELF_VIDEO_CHAT_DISCONNECTED = @"NOTIFICATION_SELF_VIDEO_CHAT_DISCONNECTED";
static NSString *const NOTIFICATION_SELF_VIDEO_CHAT_START_DISCONNECT = @"NOTIFICATION_SELF_VIDEO_CHAT_START_DISCONNECT";
static NSString *const NOTIFICATION_SELF_VIDEO_STARTED = @"NOTIFICATION_SELF_VIDEO_STARTED";
static NSString *const NOTIFICATION_SELF_VIDEO_REMOVED = @"NOTIFICATION_SELF_VIDEO_REMOVED";

static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_CHAT_CONNECTED = @"NOTIFICATION_PARTICIPANT_VIDEO_CHAT_CONNECTED";
static NSString *const NOTIFICATION_PARTICIPANT_USER_INFO_UPDATED = @"NOTIFICATION_PARTICIPANT_USER_INFO_UPDATED";
static NSString *const NOTIFICATION_TOKBOX_VIDEO_PUBLISHED = @"NOTIFICATION_TOKBOX_VIDEO_PUBLISHED";
static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_CHAT_DISCONNECTED = @"NOTIFICATION_PARTICIPANT_VIDEO_CHAT_DISCONNECTED";
static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_CHAT_DISCONNECTED_HANDLED = @"NOTIFICATION_PARTICIPANT_VIDEO_CHAT_DISCONNECTED_HANDLED";

static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_CHAT_ENABLED = @"NOTIFICATION_PARTICIPANT_VIDEO_CHAT_ENABLED";
static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_CHAT_DISABLED = @"NOTIFICATION_PARTICIPANT_VIDEO_CHAT_DISABLED";

static NSString *const NOTIFICATION_PARTICIPANT_AUDIO_ENABLED = @"NOTIFICATION_PARTICIPANT_AUDIO_ENABLED";
static NSString *const NOTIFICATION_PARTICIPANT_AUDIO_DISABLED = @"NOTIFICATION_PARTICIPANT_AUDIO_DISABLED";

static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_STARTED = @"NOTIFICATION_PARTICIPANT_VIDEO_STARTED";
static NSString *const NOTIFICATION_PARTICIPANT_VIDEO_REMOVED = @"NOTIFICATION_PARTICIPANT_VIDEO_REMOVED";

static NSString *const NOTIFICATION_VIDEOCALL_PERMISSION_GRANTED = @"NOTIFICATION_VIDEOCALL_PERMISSION_GRANTED";
static NSString *const NOTIFICATION_VIDEOCALL_PERMISSION_NOT_GRANTED = @"NOTIFICATION_VIDEOCALL_PERMISSION_NOT_GRANTED";
static NSString *const NOTIFICATION_MICROPHONE_PERMISSION_GRANTED = @"NOTIFICATION_MICROPHONE_PERMISSION_GRANTED";
static NSString *const NOTIFICATION_CAMERA_PERMISSION_GRANTED = @"NOTIFICATION_CAMERA_PERMISSION_GRANTED";
static NSString *const NOTIFICATION_CONTACT_PERMISSION_GRANTED = @"NOTIFICATION_CONTACT_PERMISSION_GRANTED";
static NSString *const NOTIFICATION_NOTIFICATION_PERMISSION_GRANTED = @"NOTIFICATION_NOTIFICATION_PERMISSION_GRANTED";
static NSString *const NOTIFICATION_SAVE_PERMISSION_GRANTED = @"NOTIFICATION_SAVE_PERMISSION_GRANTED";
static NSString *const NOTIFICATION_SAVE_PERMISSION_REJECTED = @"NOTIFICATION_SAVE_PERMISSION_REJECTED";

static NSString *const NOTIFICATION_MICROPHONE_PERMISSION_NOT_GRANTED = @"NOTIFICATION_MICROPHONE_PERMISSION_NOT_GRANTED";
static NSString *const NOTIFICATION_CAMERA_PERMISSION_NOT_GRANTED = @"NOTIFICATION_CAMERA_PERMISSION_NOT_GRANTED";
static NSString *const NOTIFICATION_CONTACT_PERMISSION_NOT_GRANTED = @"NOTIFICATION_CONTACT_PERMISSION_NOT_GRANTED";
static NSString *const NOTIFICATION_NOTIFICATION_PERMISSION_NOT_GRANTED = @"NOTIFICATION_NOTIFICATION_PERMISSION_NOT_GRANTED";
static NSString *const NOTIFICATION_CAMERA_PERMISSION_GRANTED_ENABLE_CAM = @"NOTIFICATION_CAMERA_PERMISSION_GRANTED_ENABLE_CAM";
static NSString *const NOTIFICATION_LAUNCHPAD_DATA_FETCHED = @"NOTIFICATION_LAUNCHPAD_DATA_FETCHED";

static NSString *const NOTIFICATION_AUGMENTOR_UPDATED = @"NOTIFICATION_AUGMENTOR_UPDATED";

static NSString *const NOTIFICATION_INTERNET_NOT_CONNECTED = @"NOTIFICATION_INTERNET_NOT_CONNECTED";

static NSString *const NOTIFICATION_CONTACTS_DATA_LOADED_IN_MEMORY = @"NOTIFICATION_CONTACTS_DATA_LOADED_IN_MEMORY";
static NSString *const NOTIFICATION_CONTACTS_DATA_PARTIALLLY_LOADED = @"NOTIFICATION_CONTACTS_DATA_PARTIALLLY_LOADED";
static NSString *const NOTIFICATION_ALL_CONTACTS_LOADED = @"NOTIFICATION_ALL_CONTACTS_LOADED";
static NSString *const NOTIFICATION_PARTIAL_CONTACTS_LOADED = @"NOTIFICATION_PARTIAL_CONTACTS_LOADED";

static NSString *const NOTIFICATION_FILTER_MENU_CLOSED = @"NOTIFICATION_FILTER_MENU_CLOSED";
static NSString *const NOTIFICATION_GUE_VIEW_IS_NOT_BLOCKING = @"NOTIFICATION_GUE_VIEW_IS_NOT_BLOCKING";

static NSString *const NOTIFICATION_DISCOUNT_PROVIDER_STATE_CHANGE = @"NOTIFICATION_DISCOUNT_PROVIDER_STATE_CHANGE";
static NSString *const NOTIFICATION_FILTER_OWNED = @"NOTIFICATION_FILTER_OWNED";
static NSString *const NOTIFICATION_USER_FILTERS_INITIALIZED = @"NOTIFICATION_USER_FILTERS_INITIALIZED";
static NSString *const NOTIFICATION_USER_FILTERS_STATE_UPDATED = @"NOTIFICATION_USER_FILTERS_STATE_UPDATED";

static NSString *const NOTIFICATION_SUBSCRIBER_BANDWIDTH_NOTIFICATION = @"SubscriberBandWidthNotification";
static NSString *const NOTIFICATION_GAME_STARTED = @"NOTIFICATION_GAME_STARTED";
static NSString *const NOTIFICATION_GAME_CANCELLED = @"NOTIFICATION_GAME_CANCELLED";
static NSString *const NOTIFICATION_GAME_LAUNCHED_COMPLETE = @"NOTIFICATION_GAME_LAUNCHED_COMPLETE";
static NSString *const NOTIFICATION_GAME_ENDED = @"NOTIFICATION_GAME_ENDED";
static NSString *const NOTIFICATION_PLAYER_STATE_CHANGED = @"NOTIFICATION_PLAYER_STATE_CHANGED";
static NSString *const NOTIFICATION_CHAT_VIEW_SHOWN = @"NOTIFICATION_CHAT_VIEW_SHOWN";

static NSString *const NOTIFICATION_PRESENCE_EVENT_RECEIVED = @"NOTIFICATION_PRESENCE_EVENT_RECEIVED";

static NSString *const NOTIFICATION_BROADCASTING_STATE_CHANGED = @"NOTIFICATION_BROADCASTING_STATE_CHANGED";

static NSString *const NOTIFICATION_MUTUAL_FRIEND_DATA_RECEIVED = @"NOTIFICATION_MUTUAL_FRIEND_DATA_RECEIVED";
static NSString *const NOTIFICATION_FUE_COMPLETE = @"NOTIFICATION_FUE_COMPLETE";

static NSString *const NOTIFICATION_FUE_TUTORIAL_COMPLETE = @"NOTIFICATION_FUE_TUTORIAL_COMPLETE";
static NSString *const NOTIFICATION_FUE_PHONE_NUMBER_VERIFIED = @"NOTIFICATION_FUE_PHONE_NUMBER_VERIFIED";

static NSString *const NOTIFICATION_PROFILE_GIF_UPDATE = @"NOTIFICATION_PROFILE_GIF_UPDATE";
//static NSString *const NOTIFICATION_FOR_CROWN_UPDATE = @"WINCOUNT_INCREASE_UPDATE_CROWN";
static NSString *const NOTIFICATION_FOR_UI_UPDATE_AFTER_PURCHASE = @"NOTIFICATION_FOR_UI_UPDATE_AFTER_PURCHASE";
static NSString *const NOTIFICATION_PROFILE_GIF_TEMP_UPDATE = @"NOTIFICATION_PROFILE_GIF_TEMP_UPDATE";

static NSString *const NOTIFICATION_DIFF_DATA_FETCHED = @"NOTIFICATION_DIFF_DATA_FETCHED";
static NSString *const NOTIFICATION_DIFF_REMOTE_FAILED = @"NOTIFICATION_DIFF_REMOTE_FAILED";

static NSString *const NOTIFICATION_DIFF_DATA_FETCHED_FOR_DEEPLINK = @"NOTIFICATION_DIFF_DATA_FETCHED_FOR_DEEPLINK";

//static NSString *const NOTIFICATION_ALL_BLOCKING_DIFF_FETCHED = @"NOTIFICATION_ALL_BLOCKING_DIFF_FETCHED";


static NSString *const NOTIFICATION_VIDEO_FLOW = @"NOTIFICATION_VIDEO_FLOW";
static NSString *const NOTIFICATION_JOIN_SESSION = @"NOTIFICATION_JOIN_SESSION";
static NSString *const NOTIFICATION_VIDEO_STATS_FPS = @"NOTIFICATION_VIDEO_STATS_FPS";
static NSString *const NOTIFICATION_TOKBOX_RENDERER_DEBUG = @"NOTIFICATION_TOKBOX_RENDERER_DEBUG";

static NSString *const NOTIFICATION_SESSION_START = @"NOTIFICATION_SESSION_START";
static NSString *const NOTIFICATION_NETWORK_STATS = @"NOTIFICATION_NETWORK_STATS";
static NSString *const NOTIFICATION_APP_INSTALL = @"NOTIFICATION_APP_INSTALL";
static NSString *const NOTIFICATION_OLD_DEVICE_RE_INSTALL = @"NOTIFICATION_OLD_DEVICE_RE_INSTALL";
static NSString *const NOTIFICATION_APP_LAUNCH = @"NOTIFICATION_APP_LAUNCH";
static NSString *const NOTIFICATION_APP_RESUME = @"NOTIFICATION_APP_RESUME";
static NSString *const NOTIFICATION_APP_PAUSE = @"NOTIFICATION_APP_PAUSE";
static NSString *const NOTIFICATION_APP_ENTER_BACKGROUND = @"NOTIFICATION_APP_ENTER_BACKGROUND";
static NSString *const NOTIFICATION_APP_ENTER_FOREGROUND = @"NOTIFICATION_APP_ENTER_FOREGROUND";
static NSString *const NOTIFICATION_PUBNUB_SESSION_FILTER_UPDATE = @"NOTIFICATION_PUBNUB_SESSION_FILTER_UPDATE";
static NSString *const NOTIFICATION_SCREENSHOT_CAPTURED = @"NOTIFICATION_SCREENSHOT_CAPTURED";
//game flow notifications
static NSString *const NOTIFICATION_NEW_TURN = @"NOTIFICATION_NEW_TURN";
static NSString *const NOTIFICATION_GAME_EVENT_FLOW = @"NOTIFICATION_GAME_EVENT_FLOW";
static NSString *const NOTIFICATION_GAME_END_TURN = @"NOTIFICATION_GAME_END_TURN";
static NSString *const NOTIFICATION_GAME_END_ROUND = @"NOTIFICATION_GAME_END_ROUND";
static NSString *const NOTIFICATION_GAME_FINISH_GAME = @"NOTIFICATION_GAME_FINISH_GAME";

static NSString *const NOTIFICATION_SERVER_RETRY_FAILUE = @"NOTIFICATION_SERVER_RETRY_FAILUE";
static NSString *const NOTIFICATION_GENERIC_POP_SHOWN = @"NOTIFICATION_GENERIC_POP_SHOWN";
static NSString *const NOTIFICATION_GENERIC_CLICK = @"NOTIFICATION_GENERIC_CLICK";
static NSString *const NOTIFICATION_APP_EXCEPTION = @"NOTIFICATION_APP_EXCEPTION";
static NSString *const NOTIFICATION_DISMISS_LP = @"NOTIFICATION_DISMISS_LP";
static NSString *const NOTIFICATION_SHOW_LP = @"NOTIFICATION_SHOW_LP";
static NSString *const NOTIFICATION_TAPLYTICS_BI = @"NOTIFICATION_TAPLYTICS_BI";
static NSString *const NOTIFICATION_LP_REMOVE_LOADER = @"NOTIFICATION_LP_REMOVE_LOADER";
static NSString *const NOTIFICATION_LP_VISIBLE = @"NOTIFICATION_LP_VISIBLE";

static NSString *const NOTIFICATION_SHOWING_PROFILE_MENU = @"NOTIFICATION_SHOWING_PROFILE_MENU";

static NSString *const NOTIFICATION_HIDING_PROFILE_MENU = @"NOTIFICATION_HIDING_PROFILE_MENU";

static NSString *const NOTIFICATION_HANG_UP_ON_BLOCK = @"NOTIFICATION_HANG_UP_ON_BLOCK";
static NSString *const NOTIFICATION_HANG_UP_ON_REQUEST_DISCONNECT = @"NOTIFICATION_HANG_UP_ON_REQUEST_DISCONNECT";

static NSString *const NOTIFICATION_USER_JOINED_APP = @"NOTIFICATION_USER_JOINED_APP";

static NSString *const NOTIFICATION_USER_GIF_RECORD_COMPLETE = @"NOTIFICATION_USER_GIF_RECORD_COMPLETE";
static NSString *const NOTIFICATION_USER_CAMERA_RECORD_CANCEL = @"NOTIFICATION_USER_CAMERA_RECORD_CANCEL";
static NSString *const NOTIFICATION_PUBNUB_EVENT = @"NOTIFICATION_PUBNUB_EVENT";
static NSString *const NOTIFICATION_PUBNUB_HERE_NOW_STATE = @"NOTIFICATION_PUBNUB_HERE_NOW_STATE";

static NSString *const NOTIFICATION_USER_OFFLINE = @"NOTIFICATION_USER_OFFLINE";

static NSString *const NOTIFICATION_USER_START_NEW_SESSION = @"NOTIFICATION_USER_START_NEW_SESSION";
static NSString *const NOTIFICATION_SEND_PARTICIPANT_VIDEO_START_TIME = @"NOTIFICATION_SEND_PARTICIPANT_VIDEO_START_TIME";
static NSString *const NOTIFICATION_SEND_PARTICIPANT_VIDEO_END_TIME = @"NOTIFICATION_SEND_PARTICIPANT_VIDEO_END_TIME";

static NSString *const NOTIFICATION_VIDEO_CALL_NOTIFICATION_CLICK = @"NOTIFICATION_VIDEO_CALL_NOTIFICATION_CLICK";
static NSString *const NOTIFICATION_LIVE_STREAM_NOTIFICATION_CLICK = @"NOTIFICATION_LIVE_STREAM_NOTIFICATION_CLICK";
static NSString *const NOTIFICATION_CURRENTLY_RUNNING_FACIAL_TRIGGER = @"NOTIFICATION_CURRENTLY_RUNNING_FACIAL_TRIGGER";

static NSString *const NOTIFICATION_VIEW_APPEAR = @"NOTIFICATION_VIEW_APPEAR";
static NSString *const NOTIFICATION_VIEW_DISAPPEAR = @"NOTIFICATION_VIEW_DISAPPEAR";

static NSString *const NOTIFICATION_SERVER_TRIGGERED_EVENT = @"NOTIFICATION_SERVER_TRIGGER_EVENT";

//keys - not notification names
static NSString *const CLASS_NAME_KEY = @"CLASS_NAME_KEY";

static NSString *const NOTIFICATION_LIVE_START = @"NOTIFICATION_LIVE_START";
static NSString *const NOTIFICATION_LIVE_STOP = @"NOTIFICATION_LIVE_STOP";
static NSString *const NOTIFICATION_LIVE_API = @"NOTIFICATION_LIVE_API";
static NSString *const NOTIFICATION_LIVE_FLOW = @"NOTIFICATION_LIVE_FLOW";
static NSString *const NOTIFICATION_LIVE_SETTINGS = @"NOTIFICATION_LIVE_SETTINGS";
static NSString *const NOTIFICATION_GOOGLE_SIGNIN = @"NOTIFICATION_GOOGLE_SIGNIN";
static NSString *const NOTIFICATION_CALL_ENDED_WITH_DURATION = @"NOTIFICATION_CALL_ENDED_WITH_DURATION";
static NSString *const NOTIFICATION_FILTER_APPLIED = @"NOTIFICATION_FILTER_APPLIED";

static NSString *const NOTIFICATION_SOCIAL_DISCOUNT_USED = @"NOTIFICATION_SOCIAL_DISCOUNT_USED";//only to be fired from pubnub flow
static NSString *const NOTIFICATION_ROOM_LOCKED_STATE_CHANGED = @"NOTIFICATION_ROOM_LOCKED_STATE_CHANGED";
static NSString *const NOTIFICATION_SHOW_LOCK_ROOM_CENTER_VIEW = @"NOTIFICATION_SHOW_LOCK_ROOM_CENTER_VIEW";
static NSString *const NOTIFICATION_TRIGGER_LOCK_ROOM_BI_EVENT = @"NOTIFICATION_TRIGGER_LOCK_ROOM_BI_EVENT";

static NSString *const NOTIFICATION_TOKBOX_TIMER_EXPIRY = @"NOTIFICATION_TOKBOX_TIMER_EXPIRY";
static NSString *const NOTIFICATION_PARTICIPANT_STATUS_UPDATED = @"NOTIFICATION_PARTICIPANT_STATUS_UPDATED";

static NSString *const NOTIFICATION_STREAM_SETTINGS_REFRESH = @"NOTIFICATION_STREAM_SETTINGS_REFRESH";

static NSString *const NOTIFICATION_STAR_RATING = @"NOTIFICATION_STAR_RATING";
static NSString *const NOTIFICATION_APPLY_FILTER_FOR_PARTICIPANTS = @"NOTIFICATION_APPLY_FILTER_FOR_PARTICIPANTS";
static NSString *const NOTIFICATION_APPLY_ANCHOR_FILTER_FOR_PARTICIPANTS = @"NOTIFICATION_APPLY_ANCHOR_FILTER_FOR_PARTICIPANTS";
static NSString *const NOTIFICATION_APPLY_OVERLAYS_FILTER_FOR_PARTICIPANTS = @"NOTIFICATION_APPLY_OVERLAYS_FILTER_FOR_PARTICIPANTS";

static NSString *const NOTIFICATION_PARTY_ROOM_JOINED = @"NOTIFICATION_PARTY_ROOM_JOINED";
static NSString *const NOTIFICATION_PARTY_ROOM_LEFT = @"NOTIFICATION_PARTY_ROOM_LEFT";
static NSString *const NOTIFICATION_LAUNCHPAD_SHOWN = @"NOTIFICATION_LAUNCHPAD_SHOWN";
static NSString *const NOTIFICATION_GUE_INITIALIZED = @"NOTIFICATION_GUE_INITIALIZED";
static NSString *const NOTIFICATION_INVITE_SHARE_ATTEMPTED = @"NOTIFICATION_INVITE_SHARE_ATTEMPTED";

static NSString *const NOTIFICATION_SUBSCRIBER_CALL_STARTED = @"NOTIFICATION_SUBSCRIBER_CALL_STARTED";
static NSString *const NOTIFICATION_SUBSCRIBER_CALL_CONNECTED = @"NOTIFICATION_SUBSCRIBER_CALL_CONNECTED";

static NSString *const NOTIFICATION_NOTIFICATION_RECEIVED = @"NOTIFICATION_NOTIFICATION_RECEIVED";

static NSString *const NOTIFICATION_REWARD_TASK_COMPLETION = @"NOTIFICATION_REWARD_TASK_COMPLETION";

#pragma mark UI redesign changes

static NSString *const NOTIFICATION_LAUNCHPAD_ACTION = @"NOTIFICATION_LAUNCHPAD_ACTION";
static NSString *const NOTIFICATION_LONG_PRESS_USER = @"NOTIFICATION_LONG_PRESS_USER";
static NSString *const NOTIFICATION_TAP_ON_USER = @"NOTIFICATION_TAP_ON_USER";
static NSString *const NOTIFICATION_UI_COMPONENT_STATE_UPDATE = @"NOTIFICATION_UI_COMPONENT_STATE_UPDATE";

#pragma end

static NSString *const NOTIFICATION_DISMISS_ADD_FRIEND_BLOCK_ON_VIDEO_LAYOUT = @"NOTIFICATION_DISMISS_ADD_FRIEND_BLOCK_ON_VIDEO_LAYOUT";
static NSString *const NOTIFICATION_AFTER_MENU_VISIBLE = @"NOTIFICATION_AFTER_MENU_VISIBLE";
static NSString *const NOTIFICATION_AFTER_MENU_INVISIBLE = @"NOTIFICATION_AFTER_MENU_INVISIBLE";

static NSString *const NOTIFICATION_RESET_MUTE_AFTER_CALL_DISCONNECTED = @"NOTIFICATION_RESET_MUTE_AFTER_CALL_DISCONNECTED ";

static NSString *const NOTIFICATION_CALL_HANGUP = @"NOTIFICATION_CALL_HANGUP ";

static NSString *const NOTIFICATION_SEND_PARTNER_CALL_DATA = @"NOTIFICATION_SEND_PARTNER_CALL_DATA";
static NSString *const NOTIFICATION_TOKBOX_COMMAND_RECEIVED = @"NOTIFICATION_TOKBOX_COMMAND_RECEIVED";

static NSString *const NOTIFICATION_PARTICIPANT_CALL_RECORDS = @"NOTIFICATION_PARTICIPANT_CALL_RECORDS";

static NSString *const NOTIFICATION_LIVE_ROOMS_CHANGED = @"NOTIFICATION_LIVE_ROOMS_CHANGED";
static NSString *const NOTIFICATION_USER_COUNT_UPDATED = @"NOTIFICATION_USER_COUNT_UPDATED";
static NSString *const NOTIFICATION_FRIEND_UPDATED = @"NOTIFICATION_FRIEND_UPDATED";

static NSString *const NOTIFICATION_TOKBOX_VIDEO_UNPUBLISHED = @"NOTIFICATION_TOKBOX_VIDEO_UNPUBLISHED";
static NSString *const NOTIFICATION_TOKBOX_MAX_LIMIT_REACHED = @"NOTIFICATION_TOKBOX_MAX_LIMIT_REACHED";

static NSString *const NOTIFICATION_GAME_SHOW_BECAME_LIVE_OR_HIDDEN = @"NOTIFICATION_GAME_SHOW_BECAME_LIVE_OR_HIDDEN";

static NSString *const NOTIFICATION_FRIEND_REQUEST_SENT = @"NOTIFICATION_FRIEND_REQUEST_SENT";
static NSString *const NOTIFICATION_FOLLOW_REQUEST_SENT = @"NOTIFICATION_FOLLOW_REQUEST_SENT";


#pragma mark R5P events

static NSString *const NOTIFICATION_R5P_SUBSCRIBER_PAUSE = @"NOTIFICATION_R5P_SUBSCRIBER_PAUSE";
static NSString *const NOTIFICATION_R5P_SUBSCRIBER_RESUME = @"NOTIFICATION_R5P_SUBSCRIBER_RESUME";

static NSString *const NOTIFICATION_R5P_CONNECTED = @"NOTIFICATION_R5P_CONNECTED";
static NSString *const NOTIFICATION_R5P_DISCONNECTED= @"NOTIFICATION_R5P_DISCONNECTED";
static NSString *const NOTIFICATION_R5P_ERROR = @"NOTIFICATION_R5P_ERROR";
static NSString *const NOTIFICATION_R5P_TIMEOUT = @"NOTIFICATION_R5P_TIMEOUT";
static NSString *const NOTIFICATION_R5P_CLOSE = @"NOTIFICATION_R5P_CLOSE";
static NSString *const NOTIFICATION_R5P_START_STREAMING = @"NOTIFICATION_R5P_START_STREAMING";
static NSString *const NOTIFICATION_R5P_STOP_STREAMING = @"NOTIFICATION_R5P_STOP_STREAMING";
static NSString *const NOTIFICATION_R5P_NET_STATUS = @"NOTIFICATION_R5P_NET_STATUS";
static NSString *const NOTIFICATION_R5P_VIDEO_RENDER_START = @"NOTIFICATION_R5P_VIDEO_RENDER_START";
static NSString *const NOTIFICATION_R5P_RECONNECT_STREAM = @"NOTIFICATION_R5P_RECONNECT_STREAM";

static NSString *const NOTIFICATION_R5P_PLAY_STREAM = @"NOTIFICATION_R5P_PLAY_STREAM";
//this one
static NSString *const NOTIFICATION_HOST_EXIT = @"NOTIFICATION_HOST_EXIT";
static NSString *const NOTIFICATION_GAME_SHOW_MESSAGE = @"NOTIFICATION_GAME_SHOW_MESSAGE";
static NSString *const NOTIFICATION_HOST_NOT_AVAILABLE = @"NOTIFICATION_HOST_NOT_AVAILABLE";

static NSString *const NOTIFICATION_RECRUITED_COUNT_UPDATED_FROM_REMOTE = @"NOTIFICATION_RECRUITED_COUNT_UPDATED_FROM_REMOTE";
static NSString *const NOTIFICATION_KEYS_UPDATED_FROM_REMOTE = @"NOTIFICATION_KEYS_UPDATED_FROM_REMOTE";
static NSString *const NOTIFICATION_CASH_UPDATED_FROM_REMOTE = @"NOTIFICATION_CASH_UPDATED_FROM_REMOTE";
static NSString *const NOTIFICATION_SOCIAL_DISCOUNT_UPDATED = @"NOTIFICATION_SOCIAL_DISCOUNT_UPDATED";//it is for self user
static NSString *const NOTIFICATION_WALLET_UPDATED_FROM_REMOTE = @"NOTIFICATION_WALLET_UPDATED_FROM_REMOTE";
static NSString *const NOTIFICATION_COLLECTABLES_UPDATED_FROM_REMOTE = @"NOTIFICATION_COLLECTABLES_UPDATED_FROM_REMOTE";
static NSString *const NOTIFICATION_GAME_CHAT_MESSAGE_RECEIVED = @"NOTIFICATION_GAME_CHAT_MESSAGE_RECEIVED";

static NSString *const NOTIFICATION_UPDATE_HOST_VOLUME = @"NOTIFICATION_UPDATE_HOST_VOLUME";

static NSString *const NOTIFICATION_BROADCASTER_TIER_UPDATED = @"NOTIFICATION_BROADCASTER_TIER_UPDATED";


#pragma monetary purchase
static NSString *const NOTIFICATION_USER_PURCHASE_SYNCED_ON_INSTALL = @"NOTIFICATION_USER_PURCHASE_SYNCED_ON_INSTALL";
static NSString *const NOTIFICATION_PURCHASE_FROM_STORE_COMPLETED = @"NOTIFICATION_PURCHASE_FROM_STORE_COMPLETED";
static NSString *const NOTIFICATION_PURCHASE_SUCCESS_VALIDATION_COMPLETED = @"NOTIFICATION_PURCHASE_SUCCESS_VALIDATION_COMPLETED";
static NSString *const NOTIFICATION_STORE_DATA_UPDATED = @"NOTIFICATION_STORE_DATA_UPDATED";
static NSString *const NOTIFICATION_FRIEND_COUNT_UPDATED = @"NOTIFICATION_FRIEND_COUNT_UPDATED";

static NSString *const NOTIFICATION_NETWORK_CHANGE = @"NOTIFICATION_NETWORK_CHANGE";
static NSString *const NOTIFICATION_APP_SESSION_CHANGED = @"NOTIFICATION_APP_SESSION_CHANGED";
static NSString *const NOTIFICATION_USER_CONVERT_TO_HARD_PUBLIC = @"NOTIFICATION_USER_CONVERT_TO_HARD_PUBLIC";



static NSString *const NOTIFICATION_FIRST_TIME_MONETIZATION_POPUP_SEEN = @"NOTIFICATION_FIRST_TIME_MONETIZATION_POPUP_SEEN";
static NSString *const NOTIFICATION_ADJUST_TOP_BEAK_MESSAGE = @"NOTIFICATION_ADJUST_TOP_BEAK_MESSAGE";
static NSString *const NOTIFICATION_USER_REGISTERED = @"NOTIFICATION_USER_REGISTERED";
static NSString *const NOTIFICATION_USER_RE_REGISTERED = @"NOTIFICATION_USER_RE_REGISTERED";

static NSString *const NOTIFICATION_RESERVED_USER_COUNT_UPDATED = @"NOTIFICATION_RESERVED_USER_COUNT_UPDATED";

#pragma end

#pragma collectables

static NSString *const NOTIFICATION_EVENTS_REFRESHED = @"NOTIFICATION_EVENTS_REFRESHED";
static NSString *const NOTIFICATION_USER_COLLECTABLES_UPDATED = @"NOTIFICATION_USER_COLLECTABLES_UPDATED";
static NSString *const NOTIFICATION_COLLECTABLES_REFRESHED = @"NOTIFICATION_COLLECTABLES_REFRESHED";
#pragma end



#pragma daily reward service
static NSString *const NOTIFICATION_REWARD_SERVICE_READY = @"NOTIFICATION_REWARD_SERVICE_READY";
static NSString *const NOTIFICATION_REWARD_SERVICE_STARTED = @"NOTIFICATION_REWARD_SERVICE_STARTED";

static NSString *const NOTIFICATION_REWARD_SERVICE_FINAL_REWARD_AVAILABLE = @"NOTIFICATION_REWARD_SERVICE_FINAL_REWARD_AVAILABLE";
static NSString *const NOTIFICATION_REWARD_SERVICE_COMPLETED = @"NOTIFICATION_REWARD_SERVICE_COMPLETED";
static NSString *const NOTIFICATION_REWARD_SERVICE_PREMATURE_COMPLETED = @"NOTIFICATION_REWARD_SERVICE_PREMATURE_COMPLETED";
static NSString *const NOTIFICATION_REWARD_SERVICE_EXPIRED = @"NOTIFICATION_REWARD_SERVICE_EXPIRED";

static NSString *const NOTIFICATION_REWARD_SERVICE_DAILY_REWARD_CLAIMED = @"NOTIFICATION_REWARD_SERVICE_DAILY_REWARD_CLAIMED";
static NSString *const NOTIFICATION_REWARD_SERVICE_FINAL_REWARD_CLAIMED = @"NOTIFICATION_REWARD_SERVICE_FINAL_REWARD_CLAIMED";
static NSString *const NOTIFICATION_FINAL_REWARD_CHANGED = @"NOTIFICATION_FINAL_REWARD_CHANGED";
static NSString *const NOTIFICATION_FINAL_REWARD_CLAIM_STATUS_CHANGED = @"NOTIFICATION_FINAL_REWARD_CLAIM_STATUS_CHANGED";
static NSString *const NOTIFICATION_REWARD_SERVICE_NEW_DAY = @"NOTIFICATION_REWARD_SERVICE_NEW_DAY";//for refresh of UI

static NSString *const NOTIFICATION_FORCE_REFRESH_REWARD_VIEW_CONTAINER = @"NOTIFICATION_FORCE_REFRESH_REWARD_VIEW_CONTAINER";

static NSString *const NOTIFICATION_LOBBY_REFRESH_DUE_TO_STREAK = @"NOTIFICATION_LOBBY_REFRESH_DUE_TO_STREAK";

#pragma end

#pragma mark minigame
static NSString *const NOTIFICATION_DISABLE_LOBBY_CTA = @"NOTIFICATION_DISABLE_LOBBY_CTA";
static NSString *const NOTIFICATION_UPDATE_SPIN_CTA_TXT = @"NOTIFICATION_UPDATE_SPIN_CTA_TXT";


static NSString *const NOTIFICATION_MINI_GAME_STATE_CHANGED = @"NOTIFICATION_MINI_GAME_STATE_CHANGED";
static NSString *const NOTIFICATION_MINI_GAME_REMOVE_POPUP = @"NOTIFICATION_MINI_GAME_REMOVE_POPUP";
static NSString *const NOTIFICATION_MINI_GAME_VIEW_LAYOUT_REQUEST = @"NOTIFICATION_MINI_GAME_VIEW_LAYOUT_REQUEST";
static NSString *const NOTIFICATION_MINI_GAME_VIEW_LAYOUT_ANIM_REQUEST = @"NOTIFICATION_MINI_GAME_VIEW_LAYOUT_ANIM_REQUEST";
static NSString *const NOTIFICATION_MINI_GAME_STATE_CHANGED_TO_FINAL_RESULT = @"NOTIFICATION_MINI_GAME_STATE_CHANGED_TO_FINAL_RESULT";

#pragma mark tapjoy
static NSString *const NOTIFICATION_TAPJOY_CONTENT_CHANGED = @"NOTIFICATION_TAPJOY_CONTENT_CHANGED";

static NSString *const NOTIFICATION_DIRECT_MEDIA_PLAY = @"NOTIFICATION_DIRECT_MEDIA_PLAY";
static NSString *const NOTIFICATION_SCREEN_CAPTURE_STREAM_COMPLETE = @"NOTIFICATION_SCREEN_CAPTURE_STREAM_COMPLETE";

static NSString *const NOTIFICATION_REMOVE_POPUP_IN_GAME_SHOW = @"NOTIFICATION_REMOVE_POPUP_IN_GAME_SHOW";

#pragma mark end
static NSString *const NOTIFICATION_ACHIEVEMENTS_DATA_FETCHING = @"NOTIFICATION_ACHIEVEMENTS_DATA_FETCHING";
static NSString *const NOTIFICATION_ACHIEVEMENTS_DATA_FETCHED = @"NOTIFICATION_ACHIEVEMENTS_DATA_FETCHED";

#pragma mark broadcast tournament
static NSString *const NOTIFICATION_AUTOMATIC_LEADERBOARD_DATA_FETCHING = @"NOTIFICATION_AUTOMATIC_LEADERBOARD_DATA_FETCHING";
static NSString *const NOTIFICATION_AUTOMATIC_LEADERBOARD_DATA_FETCHED = @"NOTIFICATION_AUTOMATIC_LEADERBOARD_DATA_FETCHED";
static NSString *const NOTIFICATION_BROADCAST_EVENTS_UPDATED = @"NOTIFICATION_BROADCAST_EVENTS_UPDATED";
static NSString *const NOTIFICATION_TOURNAMENT_RANK_UPDATED = @"NOTIFICATION_TOURNAMENT_RANK_UPDATED";

static NSString *const NOTIFICATION_UPDATE_PROFILE_GIF_POPUP = @"NOTIFICATION_UPDATE_PROFILE_GIF_POPUP";


static NSString *const NOTIFICATION_SHOW_FOLLOWERS_COUNTER_VIEW = @"NOTIFICATION_SHOW_FOLLOWERS_COUNTER_VIEW";
static NSString *const NOTIFICATION_HIDE_FOLLOWERS_COUNTER_VIEW = @"NOTIFICATION_HIDE_FOLLOWERS_COUNTER_VIEW";

static NSString *const NOTIFICATION_FOR_CANCEL_DECLINE_PURCHASE = @"NOTIFICATION_FOR_CANCEL_DECLINE_PURCHASE";

#pragma end

static NSString *const NOTIFICATION_ONE_MINUTE_TIMER_TICKED = @"NOTIFICATION_ONE_MINUTE_TIMER_TICKED";
static NSString *const NOTIFICATION_NETWORK_REACHABILITY_CHANGED = @"NOTIFICATION_NETWORK_REACHABILITY_CHANGED";


#pragma mark audition

static NSString *const NOTIFICATION_USER_VIDEOS_DUMMY_AUDITION_FETCHING = @"NOTIFICATION_USER_VIDEOS_DUMMY_AUDITION_FETCHING";
static NSString *const NOTIFICATION_USER_VIDEOS_DUMMY_AUDITION_FETCHED = @"NOTIFICATION_USER_VIDEOS_DUMMY_AUDITION_FETCHED";

static NSString *const NOTIFICATION_AUDITION_EVENTS_FETCHING = @"NOTIFICATION_AUDITION_EVENTS_FETCHING";
static NSString *const NOTIFICATION_AUDITION_EVENTS_UPDATED = @"NOTIFICATION_AUDITION_EVENTS_UPDATED";
static NSString *const NOTIFICATION_AUDITION_SET_AS_FIRST_TAB = @"NOTIFICATION_AUDITION_SET_AS_FIRST_TAB";

static NSString *const NOTIFICATION_CONTESTS_EVENTS_UPDATED = @"NOTIFICATION_CONTESTS_EVENTS_UPDATED";
static NSString *const NOTIFICATION_CONTESTS_EVENTS_FETCHING = @"NOTIFICATION_CONTESTS_EVENTS_FETCHING";

static NSString *const NOTIFICATION_BATTLE_EVENTS_UPDATED = @"NOTIFICATION_BATTLE_EVENTS_UPDATED";
static NSString *const NOTIFICATION_GAMES_DATA_FETCHED_SAVED = @"NOTIFICATION_GAMES_DATA_FETCHED_SAVED";
static NSString *const NOTIFICATION_APP_PARAM_DATA_FETCHED_SAVED = @"NOTIFICATION_APP_PARAM_DATA_FETCHED_SAVED";
static NSString *const NOTIFICATION_GIFT_DATA_FETCHED_SAVED = @"NOTIFICATION_GIFT_DATA_FETCHED_SAVED";
static NSString *const NOTIFICATION_GEO_GROUP_DATA_FETCHED_SAVED = @"NOTIFICATION_GEO_GROUP_DATA_FETCHED_SAVED";

static NSString *const NOTIFICATION_CONTESTS_DATA_FETCHED_SAVED = @"NOTIFICATION_CONTESTS_DATA_FETCHED_SAVED";
static NSString *const NOTIFICATION_BATTLES_DATA_FETCHED_SAVED = @"NOTIFICATION_BATTLES_DATA_FETCHED_SAVED";
static NSString *const NOTIFICATION_PRODUCTS_DATA_FETCHED_SAVED = @"NOTIFICATION_PRODUCTS_DATA_FETCHED_SAVED";
static NSString *const NOTIFICATION_EVENTS_DATA_FETCHED_SAVED = @"NOTIFICATION_EVENTS_DATA_FETCHED_SAVED";

static NSString *const NOTIFICATION_AUDITION_ENTRIES_FETCHING = @"NOTIFICATION_AUDITION_ENTRIES_FETCHING";
static NSString *const NOTIFICATION_AUDITION_ENTRIES_UPDATED = @"NOTIFICATION_AUDITION_ENTRIES_UPDATED";

static NSString *const NOTIFICATION_AUDITION_ENTRY_LIKE_COUNT_TO_SERVER_UPDATING = @"NOTIFICATION_AUDITION_ENTRY_LIKE_COUNT_TO_SERVER_UPDATING";
static NSString *const NOTIFICATION_AUDITION_ENTRY_LIKE_COUNT_TO_SERVER_UPDATED = @"NOTIFICATION_AUDITION_ENTRY_LIKE_COUNT_TO_SERVER_UPDATED";
static NSString *const NOTIFICATION_PLAYED_AUDITION_ENTRY_CHANGED = @"NOTIFICATION_PLAYED_AUDITION_ENTRY_CHANGED";

static NSString *const NOTIFICATION_USER_AUDITION_ENTRY_APPENDED = @"NOTIFICATION_USER_AUDITION_ENTRY_APPENDED";

static NSString *const NOTIFICATION_USER_AUDITION_BEFORE_SHARE = @"NOTIFICATION_USER_AUDITION_BEFORE_SHARE";
static NSString *const NOTIFICATION_USER_AUDITION_AFTER_POST = @"NOTIFICATION_USER_AUDITION_AFTER_POST";
static NSString *const NOTIFICATION_USER_AUDITION_EXIT_AFTER_SHARE = @"NOTIFICATION_USER_AUDITION_EXIT_AFTER_SHARE";


static NSString *const NOTIFICATION_STRAIGHT_FACE_DETECTED = @"NOTIFICATION_STRAIGHT_FACE_DETECTED";
static NSString *const NOTIFICATION_FACE_RECT_DETECTED = @"NOTIFICATION_FACE_RECT_DETECTED";
static NSString *const NOTIFICATION_STRAIGHT_FACE_CAPTURED = @"NOTIFICATION_STRAIGHT_FACE_CAPTURED";//it means final detection done

static NSString *const NOTIFICATION_FACE_SWAP_PROCESS = @"NOTIFICATION_FACE_SWAP_PROCESS";

static NSString *const NOTIFICATION_TOGGLE_CAPTURE_VIDEO = @"NOTIFICATION_TOGGLE_CAPTURE_VIDEO";

static NSString *const NOTIFICATION_FACE_TILT_LOG_TEXT = @"NOTIFICATION_FACE_TILT_LOG_TEXT";

static NSString *const NOTIFICATION_HIDE_SHARE_ROLL_VIEW = @"NOTIFICATION_HIDE_SHARE_ROLL_VIEW";

#pragma end

#pragma mark stripe
static NSString *const NOTIFICATION_STRIPE_PAYMENT_FINISHED = @"NOTIFICATION_STRIPE_PAYMENT_FINISHED";
static NSString *const NOTIFICATION_STRIPE_PAYMENT_WITH_SERVER_PROCESSING_FINISHED = @"NOTIFICATION_STRIPE_PAYMENT_WITH_SERVER_PROCESSING_FINISHED";
static NSString *const NOTIFICATION_STRIPE_PAYMENT_SUCCESS_REFRESH_VIEW = @"NOTIFICATION_STRIPE_PAYMENT_SUCCESS_REFRESH_VIEW";

static NSString *const NOTIFICATION_LEDGER_ENTRIES_FETCHING = @"NOTIFICATION_LEDGER_ENTRIES_FETCHING";
static NSString *const NOTIFICATION_LEDGER_ENTRIES_UPDATED = @"NOTIFICATION_LEDGER_ENTRIES_UPDATED";

static NSString *const NOTIFICATION_FRIEND_REQUEST_ACCEPTED = @"NOTIFICATION_FRIEND_REQUEST_ACCEPTED";

static NSString *const NOTIFICATION_PG_FUE = @"NOTIFICATION_PG_FUE";

#pragma end

#endif /* NotificationNameConstant_h */
